#!/usr/bin/env bash
# Configures a brand new Ubuntu server with Nginx and adds custom HTTP response header X-Served-By set to the server hostname

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx

HOSTNAME=$(hostname)

printf "server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\troot /var/www/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\tserver_name _;\n\tadd_header X-Served-By %s always;\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}\n" "$HOSTNAME" > /etc/nginx/sites-available/default

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -t
if command -v systemctl > /dev/null 2>&1; then
    systemctl enable nginx
    systemctl restart nginx
else
    service nginx restart
fi
# shellcheck disable=SC2154
