#!/usr/bin/env bash
# Configures a brand new Ubuntu server with Nginx and adds custom HTTP response header X-Served-By set to the server hostname

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx

HOSTNAME=$(hostname)

cat > /etc/nginx/conf.d/custom_header.conf << EOF
add_header X-Served-By $HOSTNAME always;
EOF

if command -v systemctl > /dev/null 2>&1; then
    systemctl restart nginx
else
    service nginx restart
fi
# shellcheck disable=SC2154
