#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx and a 301 redirect for /redirect_me

apt-get update -y
apt-get install -y nginx

# Use sed to replace 'location / {' line and insert redirect block before it
sed -i 's|location / {|location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {|' /etc/nginx/sites-available/default

service nginx restart
