#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx and a 301 redirect for /redirect_me

apt-get update -y
apt-get install -y nginx

cat > /etc/nginx/sites-available/default << 'EOF'
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	root /usr/share/nginx/html;
	index index.html index.htm;

	server_name localhost;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location / {
		try_files $uri $uri/ =404;
	}
}
EOF

nginx -t
service nginx restart
